### ISSUE TITLE
KeyError: 'locations'

### ISSUE THREAD

**Issue by pakair** [DavidMetcalfe/Google-Maps-Location-History-Parser#1]
saved your code as lh.py, fixed the filename to read, '2020_FEBRUARY.json' but upon running your code I get ...
$ python lh.py
Traceback (most recent call last):
  File "lh.py", line 11, in <module>
    for i in data['locations']:
KeyError: 'locations'

**Comment by DavidMetcalfe** [comment]
Please note the filename contained in the [instructions](https://github.com/DavidMetcalfe/Google-Maps-Location-History-Parser#parse-your-export-data): **"Location History.json"**

Please rename and the script should work fine.

**Comment by DavidMetcalfe** [comment]
Reopening this — the original "use the right filename" diagnosis was actually a format change in Google Takeout, not a filename typo.

Around 2020, Google restructured the Location History export:

* **Old format** (pre-2020): a single `Location History.json` file with a top-level `locations` array of `{latitudeE7, longitudeE7}` dicts.
* **New format** (2020+): a `Semantic Location History/<year>/` folder of per-month JSON files (e.g. `2020_FEBRUARY.json`) with a top-level `timelineObjects` array of `placeVisit` and `activitySegment` dicts. `Settings.json` holds reporting metadata, not history.

So a user pointing the script at `2020_FEBRUARY.json` correctly does *not* have a `locations` key — the file uses `timelineObjects` with a different entry shape. Renaming alone wouldn't have fixed it; the script's data extraction was tied to the old schema.

PR #3 ([#3](https://github.com/DavidMetcalfe/Google-Maps-Location-History-Parser/pull/3)) fixes the underlying schema mismatch:

* Accepts a file or folder path as the first argument (defaults to `Location History.json` for backward compatibility).
* Walks JSON files in a given folder recursively and skips `Settings.json`.
* Extracts coordinates from `placeVisit.location`, `activitySegment.startLocation`, and `activitySegment.endLocation` (all E7 integers), plus the legacy top-level `latitudeE7`/`longitudeE7` entries.
* README updated with the new usage patterns.
